<a href="https://colab.research.google.com/github/aashut-in/ML-and-DA-TRAINING/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

In [29]:
array = np.array([10, 20, 30, 40, 50])
print(array)

[10 20 30 40 50]


In [30]:
array = np.array([[10, 20, 30],
                  [60, 40, 50]])
print(array)

[[10 20 30]
 [60 40 50]]


In [31]:
array = np.array([[[10, 20],[30, 40]],
                  [[50, 60], [70, 80]]])
print(array)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [32]:
print(array.ndim)

3


In [33]:
print(array.shape)
print(array.size)
print()

(2, 2, 2)
8



In [34]:
arr = np.array([10, 20, 30, 40, 50]) #defining 1D array

In [35]:
print(np.mean(arr)) #to find the average

30.0


In [36]:
print(np.median(arr)) #to find the median value

30.0


In [37]:
#Variance and Std deviation:
# Variance measures how far each number in the set is from the mean. It is calculated by taking the differences between each number and the mean, squaring the differences, and then averaging them.
# Standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the values are spread out over a wider range.

In [38]:
print(np.max(arr)) #max/highest value

50


In [39]:
print(np.min(arr)) #min/lowest value

10


In [40]:
print(np.sum(arr)) #total value

150


In [41]:
print(np.std(arr))

14.142135623730951


In [42]:
print(np.var(arr))

200.0


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [44]:
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

[1 2 3 4]


In [45]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [46]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.arange(1, 11) # array in a particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.random.rand(5) # give random numbers below 1

array([0.12015806, 0.75661142, 0.18290307, 0.95826108, 0.23554757])

In [51]:
np.random.randint(1, 100, size = 10) # give random integers

array([46, 36, 55, 22, 71, 51, 42, 94, 22, 74])

In [52]:
arr = np.array([5, 2,  9, 1])
print(np.sort(arr))

[1 2 5 9]


In [27]:
arr = np.array([1,2,2,3,3,4])

print(np.unique(arr))

[1 2 3 4]


In [55]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [54]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr,3))b

[array([1, 2]), array([3, 4]), array([5, 6])]


In [57]:
arr = np.array([10,20,30,40,50])

print(arr[arr>25])

[30 40 50]
